name = "ammail"
main = "src/index.ts"
compatibility_date = "2024-01-01"
workers_dev = true

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "ammail-db"
database_id = "348c3db2-67e6-4187-8c10-51b054e33cbf"

# Environment variables
[vars]
API_KEY = "123"
TELEGRAM_BOT_TOKEN = "7502015333:AAE59oY11x737Q8191162005jJf49945V78"

# Routes
[[routes]]
pattern = "ammail.toirate.com/*"
zone_name = "toirate.com"
